self.angle = 0
self.throwcon = 1
self.angledraw = 1
self.image_xscale = 2
self.image_yscale = 2
self.radius = 300
self.anglespeed = 2
self.rx = (self.x + 70)
self.ry = (self.y + 30)
self.ralspeed = 26
self.ralgrav = 1
self.fro = 0
self.mypower = 15
self.maxpower = 30
self.minpower = 15
self.powerdir = 1
self.powerspeed = 0.6
self.throwready = 0
self.throwalpha = 0
self.activatethrow = 0
