self.con = 0
self.htimer = 0
self.image_xscale = 4
self.image_yscale = 4
self.active = 0
self.image_alpha = 0
self.x = (obj_heart.x + 8)
self.y = (obj_heart.y + 8)
self.image_angle = -90
self.joker = 0
self.damage = 100
self.grazed = 0
self.grazepoints = 5
self.timepoints = 0
self.inv = 60
self.grazetimer = 0
