self.tsiner = 0
global.tensionselect = 0
self.apparent = global.tension
self.current = global.tension
self.change = 0
self.changetimer = 15
self.red = 0
self.redtimer = 0
self.xx = __view_get(e__VW.XView, 0)
self.yy = __view_get(e__VW.YView, 0)
self.y = (self.yy + 40)
self.x = (self.xx - 40)
self.hspeed = 13
self.friction = 1
self.flashsiner = 0
