self.roomname = " "@24
if (self.argument0 == 0)
    self.roomname = "---"@2273
if (self.argument0 == 2)
    self.roomname = scr_84_get_lang_string("scr_roomname_slash_scr_roomname_gml_3_0"@2757)
if (self.argument0 == 35)
    self.roomname = scr_84_get_lang_string("scr_roomname_slash_scr_roomname_gml_4_0"@2758)
if (self.argument0 == 40)
    self.roomname = scr_84_get_lang_string("scr_roomname_slash_scr_roomname_gml_5_0"@2759)
if (self.argument0 == 45)
    self.roomname = scr_84_get_lang_string("scr_roomname_slash_scr_roomname_gml_6_0"@2760)
if (self.argument0 == 49)
    self.roomname = scr_84_get_lang_string("scr_roomname_slash_scr_roomname_gml_7_0"@2761)
if (self.argument0 == 59)
    self.roomname = scr_84_get_lang_string("scr_roomname_slash_scr_roomname_gml_8_0"@2762)
if (self.argument0 == 68)
    self.roomname = scr_84_get_lang_string("scr_roomname_slash_scr_roomname_gml_9_0"@2763)
if (self.argument0 == 71)
    self.roomname = scr_84_get_lang_string("scr_roomname_slash_scr_roomname_gml_10_0"@2764)
if (self.argument0 == 73)
    self.roomname = scr_84_get_lang_string("scr_roomname_slash_scr_roomname_gml_11_0"@2765)
if (self.argument0 == 82)
    self.roomname = scr_84_get_lang_string("scr_roomname_slash_scr_roomname_gml_12_0"@2766)
if (self.argument0 == 90)
    self.roomname = scr_84_get_lang_string("scr_roomname_slash_scr_roomname_gml_13_0"@2767)
if (self.argument0 == 96)
    self.roomname = scr_84_get_lang_string("scr_roomname_slash_scr_roomname_gml_14_0"@2768)
if (self.argument0 == 97)
    self.roomname = scr_84_get_lang_string("scr_roomname_slash_scr_roomname_gml_15_0"@2769)
if (self.argument0 == 107)
    self.roomname = scr_84_get_lang_string("scr_roomname_slash_scr_roomname_gml_16_0"@2770)
if (self.argument0 == 114)
    self.roomname = scr_84_get_lang_string("scr_roomname_slash_scr_roomname_gml_17_0"@2771)
if (self.argument0 == 123)
    self.roomname = scr_84_get_lang_string("scr_roomname_slash_scr_roomname_gml_18_0"@2772)
if (self.argument0 == 126)
    self.roomname = scr_84_get_lang_string("scr_roomname_slash_scr_roomname_gml_19_0"@2773)
if (self.argument0 == 111)
    self.roomname = scr_84_get_lang_string("scr_roomname_slash_scr_roomname_gml_20_0"@2774)
if (self.argument0 == 56)
{
    if (global.lang == "en"@2775)
        self.roomname = "Field - Maze of Death"@2776
    if (global.lang == "ja"@1566)
        self.roomname = "平原 - 死の迷路"@2777
}
return self.roomname
