self.xx = __view_get(0, 0)
self.yy = __view_get(1, 0)
self.condition = 0
self.attackno = 0
self.attack = 0
self.image_xscale = 2
self.image_yscale = 2
self.x = (self.xx + 470)
self.y = (self.yy + 70)
self.active = 1
self.faketimer = 0
self.faketimermax = 180
self.timeruse = 0
self.image_speed = 0.334
