self.visible = 0
self.type = choose(0, 1, 2, 3)
self.y = -80
self.image_xscale = 2
self.image_yscale = 2
self.con = 0
self.timer = 0
self.image_speed = 0
self.vspeed = 10
self.maxtimer = (20 + random(16))
self.explodedraw = 0
