self.image_speed = 0
self.image_index = 0
self.x = 226
self.y = 85
self.con = 0
self.heartwagon = 0
self.sprite_index = spr_dkris_bedstruggle
self.wagon = scr_marker(235, 165, spr_wheelbarrow_small)
self.cageshake = 0
self.cageamt = 0
self.shaketimer = 0
self.heartx = 0
self.hearty = 0
