if (global.mnfight != 2)
    instance_destroy()
if (self.x < (__view_get(0, 0) - self.sprite_width))
    instance_destroy()
if (self.x > ((__view_get(0, 0) + 640) + self.sprite_width))
    instance_destroy()
if (self.y < (__view_get(1, 0) - self.sprite_height))
    instance_destroy()
if (self.y > ((__view_get(1, 0) + 480) + self.sprite_height))
    instance_destroy()
