self.stringpos = 0
self.mystring = " "@24
self.part = 1
self.partstring = " "@24
self.type = 0
self.rate = 1
self.active = 0
self.finished = 0
self.mycolor = 8388736
self.alarm[0] = 1
self.getrid = 0
self.writergod = 6
self.nowdir = 90
self.facealpha = 0
