self.grazed = 0
self.grazepoints = 10
self.timepoints = 0
self.target = 0
self.dont = 1
self.inv = 60
self.damage = 20
self.spec = 0
if (global.hp[1] <= (global.maxhp[1] / 2))
    self.damage = 10
if (global.hp[1] <= (global.maxhp[1] / 4))
    self.damage = 5
self.image_xscale = 2
self.image_yscale = 2
self.loop = 0
self.lcon = 0
self.flip = 0
self.ltimer = 0
self.btimer = 0
self.endcon = 0
self.racecon = 0
self.yy = __view_get(e__VW.YView, 0)
self.xx = __view_get(e__VW.XView, 0)
self.topy = (self.yy + 120)
self.bottomy = (self.yy + 250)
