self.roomname = " "
if (self.argument0 == 0)
    self.roomname = "---"
if (self.argument0 == 2)
    self.roomname = scr_84_get_lang_string("scr_roomname_slash_scr_roomname_gml_3_0")
if (self.argument0 == 35)
    self.roomname = scr_84_get_lang_string("scr_roomname_slash_scr_roomname_gml_4_0")
if (self.argument0 == 40)
    self.roomname = scr_84_get_lang_string("scr_roomname_slash_scr_roomname_gml_5_0")
if (self.argument0 == 45)
    self.roomname = scr_84_get_lang_string("scr_roomname_slash_scr_roomname_gml_6_0")
if (self.argument0 == 49)
    self.roomname = scr_84_get_lang_string("scr_roomname_slash_scr_roomname_gml_7_0")
if (self.argument0 == 59)
    self.roomname = scr_84_get_lang_string("scr_roomname_slash_scr_roomname_gml_8_0")
if (self.argument0 == 68)
    self.roomname = scr_84_get_lang_string("scr_roomname_slash_scr_roomname_gml_9_0")
if (self.argument0 == 71)
    self.roomname = scr_84_get_lang_string("scr_roomname_slash_scr_roomname_gml_10_0")
if (self.argument0 == 73)
    self.roomname = scr_84_get_lang_string("scr_roomname_slash_scr_roomname_gml_11_0")
if (self.argument0 == 82)
    self.roomname = scr_84_get_lang_string("scr_roomname_slash_scr_roomname_gml_12_0")
if (self.argument0 == 90)
    self.roomname = scr_84_get_lang_string("scr_roomname_slash_scr_roomname_gml_13_0")
if (self.argument0 == 96)
    self.roomname = scr_84_get_lang_string("scr_roomname_slash_scr_roomname_gml_14_0")
if (self.argument0 == 97)
    self.roomname = scr_84_get_lang_string("scr_roomname_slash_scr_roomname_gml_15_0")
if (self.argument0 == 107)
    self.roomname = scr_84_get_lang_string("scr_roomname_slash_scr_roomname_gml_16_0")
if (self.argument0 == 114)
    self.roomname = scr_84_get_lang_string("scr_roomname_slash_scr_roomname_gml_17_0")
if (self.argument0 == 123)
    self.roomname = scr_84_get_lang_string("scr_roomname_slash_scr_roomname_gml_18_0")
if (self.argument0 == 126)
    self.roomname = scr_84_get_lang_string("scr_roomname_slash_scr_roomname_gml_19_0")
if (self.argument0 == 111)
    self.roomname = scr_84_get_lang_string("scr_roomname_slash_scr_roomname_gml_20_0")
if (self.argument0 == 56)
{
    if (global.lang == "en")
        self.roomname = "Field - Maze of Death"
    if (global.lang == "ja")
        self.roomname = "平原 - 死の迷路"
}
return self.roomname;
