self.image_speed = 0
self.con = 0
self.throw = 0
self.buffer = 0
self.throwtimer = 0
self.image_xscale = 2
self.image_yscale = 2
self.dir = choose(1, -1)
self.gravity = 1
self.vspeed = -14
self.hspeed = (self.dir * random(2))
