self.siner = 0
self.alpha = 0.2
self.xstretch = 1
self.ystretch = 1
self.o_insurance = 0
self.depth = (4 + instance_number(self.object_index))
self.OBSPEED = 0.02
self.b_insurance = 0
self.b_insurance = -0.2
