draw_set_color(self.image_blend)
draw_set_alpha(self.image_alpha)
scr_84_set_draw_font("main"@1558)
draw_text(self.x, self.y, string_hash_to_newline(self.msg))
draw_set_alpha(1)
self.image_alpha = (self.image_alpha - 0.1)
if (self.image_alpha < 0)
    instance_destroy()
if (global.interact != 5)
    instance_destroy()
