global.entrance = 23
instance_create(0, 0, obj_persistentfadein)
if (self.room == room_town_south)
    room_goto(room_hospital_lobby)
if (self.room == room_hospital_lobby)
    room_goto(room_town_south)
if (self.room == room_town_mid)
    room_goto(room_alphysalley)
if (self.room == room_alphysalley)
    room_goto(room_town_mid)
if (self.room == room_town_north)
    room_goto(room_beach)
if (self.room == room_beach)
    room_goto(room_town_north)
