self.image_xscale = 2
self.image_yscale = 2
self.counter = 0
self.image_angle = 0
self.seizure = 0
self.hspeed = (-7.6 - random(1.5))
self.vspeed = (-2 + random(4))
self.gravity = 0.13
self.gravity_direction = 0
self.active = 1
self.timepoints = 4
self.grazepoints = 4
self.damage = 30
self.grazed = 0
